### ISSUE TITLE
 `FileNotFoundError: [Errno 2]` when running source `./setup-iOS.sh 3.11. `

### ISSUE THREAD

**Issue by noelmullankuzhy** [beeware/mobile-forge#36]
### Describe the bug

Mobile forge build fails when running `source ./setup-iOS.sh 3.11` because It cannot find dependencies.

`FileNotFoundError: [Errno 2] No such file or directory: 'dist/bzip2-1.0.8-1-py3-none-ios_12_0_iphoneos_arm64.whl'`

This error is repeated for `bzip2`, `xz`, `libffi`, `openssl` and for platforms `iphoneos_arm64`, `iphonesimulator_arm64`, `iphonesimulator_x86_64`.

[Terminal Output Mobile-Forge Build Fail.txt](https://github.com/beeware/mobile-forge/files/14586185/Terminal.Output.Mobile-Forge.Build.Fail.txt)

Upon closer inspection of the `Dist` directory only `ninja` for all platforms are available. 
I have inspected the `setup-iOS.sh` and found that only `ninja` is configured to download.

```
> # Create wheels for ninja that can be installed in the host environment
> if ! [ -f "dist/ninja-1.11.1-py3-none-ios_12_0_iphoneos_arm64.whl" ]; then
>     echo "Downloading Ninja"
>     python -m pip wheel --no-deps -w dist ninja==1.11.1
>     mv dist/ninja-1.11.1-*.whl dist/ninja-1.11.1-py3-none-ios_12_0_iphoneos_arm64.whl
>     cp dist/ninja-1.11.1-py3-none-ios_12_0_iphoneos_arm64.whl dist/ninja-1.11.1-py3-none-ios_12_0_iphonesimulator_x86_64.whl
>     cp dist/ninja-1.11.1-py3-none-ios_12_0_iphoneos_arm64.whl dist/ninja-1.11.1-py3-none-ios_12_0_iphonesimulator_arm64.whl
> fi
```
On further inspection of the following line  I understand that `setup-iOS.sh` uses `make_dep_wheels.py` to generate the wheels for `bzip2`, `xz`, `libffi`, `openssl`
```
echo "Building platform dependency wheels..."
python -m make_dep_wheels iOS
```
This step is trowing the errors. But rest of the `source ./setup-iOS.sh 3.11` executes even when error is thrown by `make_dep_wheels.py`

I was able to resolve the issue by doing the following steps.

1. `$ export PYTHON_APPLE_SUPPORT=/path/to/Python-Apple-support`
2. `$ git clone https://github.com/beeware/mobile-forge.git`
3. Create a folder `dist` in `mobile-forge`
4. Copy the respective files from `Python-Apple-Support/downloads`   to `mobile-forge/dist`
These files can also be downloaded from  in `https://anaconda.org/beeware/repo` 
6. $ `cd mobile-forge`
7. $ `source ./setup-iOS.sh 3.11`

[Terminal Output Mobile Forge Build Success.txt](https://github.com/beeware/mobile-forge/files/14586310/Terminal.Output.Mobile.Forge.Build.Success.txt)

### Steps to reproduce

1. Set an environment variable declaring the location of your Python-Apple-support checkout:

```
$ export PYTHON_APPLE_SUPPORT=/path/to/Python-Apple-support
```

2. Clone this repository, and run the activate script for the Python version you want to use:

```
$ git clone https://github.com/beeware/mobile-forge.git
$ cd mobile-forge
$ source ./setup-iOS.sh 3.11
```

### Expected behavior

Running $ `source ./setup-iOS.sh 3.11` completes without failure.

### Environment

- Operating System: Mac OS Sonoma Version 14.3.1 (23D60)
- Python version: 3.11.6 (Assumed from Python-Apple-Support make file)
- Software versions: 
  - Python Apple Support:  branch 3.11
  -Mobile Forge: branch main
  - ...

### Logs

```
`FileNotFoundError: [Errno 2] No such file or directory: 'dist/bzip2-1.0.8-1-py3-none-ios_12_0_iphoneos_arm64.whl'`

`FileNotFoundError: [Errno 2] No such file or directory: 'dist/xz-5.4.4-1-py3-none-ios_12_0_iphoneos_arm64.whl'`

`FileNotFoundError: [Errno 2] No such file or directory: 'dist/libffi-3.4.4-1-py3-none-ios_12_0_iphoneos_arm64.whl'`

`FileNotFoundError: [Errno 2] No such file or directory: 'dist/openssl-3.0.12-1-py3-none-ios_12_0_iphoneos_arm64.whl'`

`FileNotFoundError: [Errno 2] No such file or directory: 'dist/bzip2-1.0.8-1-py3-none-ios_12_0_iphonesimulator_arm64.whl'`

`FileNotFoundError: [Errno 2] No such file or directory: 'dist/xz-5.4.4-1-py3-none-ios_12_0_iphonesimulator_arm64.whl'`

`FileNotFoundError: [Errno 2] No such file or directory: 'dist/libffi-3.4.4-1-py3-none-ios_12_0_iphonesimulator_arm64.whl'`

`FileNotFoundError: [Errno 2] No such file or directory: 'dist/openssl-3.0.12-1-py3-none-ios_12_0_iphonesimulator_arm64.whl'`

`FileNotFoundError: [Errno 2] No such file or directory: 'dist/bzip2-1.0.8-1-py3-none-ios_12_0_iphonesimulator_x86_64.whl'`

`FileNotFoundError: [Errno 2] No such file or directory: 'dist/xz-5.4.4-1-py3-none-ios_12_0_iphonesimulator_x86_64.whl'`

`FileNotFoundError: [Errno 2] No such file or directory: 'dist/libffi-3.4.4-1-py3-none-ios_12_0_iphonesimulator_x86_64.whl'`

`FileNotFoundError: [Errno 2] No such file or directory: 'dist/openssl-3.0.12-1-py3-none-ios_12_0_iphonesimulator_x86_64.whl'`
```

**Comment by freakboy3742** [comment]
Thanks for the report - it looks like there's some improvements needed here in error handling. I've addressed this as part of #38; the `make_dep_wheels.py` process should now raise an error if it can't find the installed library, and the overall setup process should halt at that point.

**Comment by noelmullankuzhy** [comment]
Sorry to bother you again.

I have coned the latest commit and tried to build.
I have added the `PYTHON_APPLE_SUPPORT` and `LANG` Environment Variables temporarily to the terminal before cloning the repository.  But running  `source ./setup-iOS.sh 3.11` still fails with similar error. I have attached the Terminal Output below

[Terminal Output Mobile-Forge Issue 38 Test Build Fail.txt](https://github.com/beeware/mobile-forge/files/14596020/Terminal.Output.Mobile-Forge.Issue.38.Test.Build.Fail.txt)

And here are the environment variables.

[Terminal Output Print Env.txt](https://github.com/beeware/mobile-forge/files/14595984/Terminal.Output.Print.Env.txt)

Here I can see `TMPDIR`, `USER`, `HOME`, `TERM`, `LANG`, and `PYTHON_APPLE_SUPPORT`
Are these setup correctly? Anything else that needs to be taken care of?

Thank you so much for the quick support.

**Comment by freakboy3742** [comment]
Ugh - this one is *really* dumb (on my part). It's assuming the `dist` folder already exists when it tries to create the dependency wheels. What's really annoying is that the creation of the `ninja` wheel *does* create the dist folder - so if you deactivate the and delete the `venv3.11` environment and re-run `source ./setup-iOS.sh 3.11`, it will work.

I'll push an update to make sure the dist folder is created as part of packaging wheels. Apologies again for the inconvenience.

**Comment by freakboy3742** [comment]
A fix for this is now in place; if you update your mobile-forge checkout, it should be resilient to a missing `dist` folder.

**Comment by noelmullankuzhy** [comment]
Ah. That's alright. It happens to the best of us. I will try that. I will move the code that create `ninja` wheel above the `make_dep_wheel.py` call. Explicitly making the  `dist` folder will be the best approach.

**Comment by freakboy3742** [comment]
No need to move anything - the change is already in place.

**Comment by noelmullankuzhy** [comment]
Thank you.
